# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5869defbf61e195546b6466774dddac75f29b12d0d1b2ce4cb97fc436209f0b906c58b68b14bdf855ce577e74fbab1dca2e2822c733a8e913b4bf8953c9207b1

test:
  secret_key_base: 226f49becd83a19609cf2eb5dfb0d1c2a63c1b29e60885d93ca5c3212ac328a89a488b2cd56d4d2838476a4550760bd3e1a7f2a2c3837dfbbfe32843a2e05adf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
